version: '2'
services:
  hbase:
    container_name: hbase
    hostname: smartsight
    image: dockercompose_busybox:latest
    restart: always
    networks:
      - smartsight
  kafka:
    container_name: kafka
    image: dockercompose_busybox:latest
    restart: always
    network_mode: "service:hbase"
  logstash:
    container_name: logstash
    image: dockercompose_busybox:latest
    restart: always
    network_mode: "service:hbase"
  collector:
    container_name: collector
    image: dockercompose_busybox:latest
    restart: always
    network_mode: "service:hbase"
  kernel:
    container_name: kernel
    image: dockercompose_busybox:latest
    restart: always
    network_mode: "service:hbase"
  portal:
    container_name: portal
    image: dockercompose_busybox:latest
    restart: always
    network_mode: "service:hbase"
  policy:
    container_name: policy
    image: dockercompose_busybox:latest
    restart: always
    network_mode: "service:hbase"
  nfvtrace:
    container_name: nfvtrace
    image: dockercompose_busybox:latest
    restart: always
    network_mode: "service:hbase"
  dbmonitor:
    container_name: dbmonitor
    image: dockercompose_busybox:latest
    restart: always
    network_mode: "service:hbase"
  cep:
    container_name: cep
    image: dockercompose_busybox:latest
    restart: always
    network_mode: "service:hbase"

networks:
  smartsight:
    driver: bridge

