apiVersion: v1
kind: ReplicationController
metadata:
  name: jenkins-master
  labels:
    name: jenkins-master
spec:
  replicas: 3
  selector:
    name: jenkins-master
  template:
    metadata:
      labels:
        name: jenkins-master
    spec:
      containers:
      - name: master
        image: 10.62.100.97:5000/jenkinsci/jenkins:2.11
        ports:
        - containerPort: 8080
