FROM  ubuntu_ssh:latest

MAINTAINER "goldonship" <goldon.qian@gmail.com>

ENV JAVA_HOME /usr/local/jdk1.8.0_101

ADD jdk-8u101-linux-x64.tar.gz /usr/local

RUN ln -sv /usr/local/jdk1.8.0_101/bin/java /usr/bin/java 
