version: '2'
services:
  kube-etcd:
    container_name: kube-etcd
    hostname: kube-etcd
    image: etcd:v3.0.15
    restart: always
    expose:
      - "4001"
      - "7001"
    ports:
      - "4001:4001"
      - "7001:7001"
    network_mode: "bridge"

  kube-apiserver:
    container_name: kube-apiserver
    hostname: kube-apiserver
    image: kube-apiserver:latest
    restart: always
    expose:
      - "8080"
    ports:
      - "8080:8080"
    network_mode: "bridge"
    links:
      - kube-etcd:etcd

  kube-controller-manager:
    container_name: kube-controller-manager
    hostname: kube-controller-manager
    image: kube-controller-manager:latest
    restart: always
    network_mode: "bridge"
    links:
      - kube-apiserver

  kube-scheduler:
    container_name: kube-scheduler
    hostname: kube-scheduler
    image: kube-scheduler:latest
    restart: always
    network_mode: "bridge"
    links:
      - kube-apiserver
  
  kubelet:
    container_name: kubelet
    hostname: kubelet
    image: kubelet:latest
    restart: always
    network_mode: "bridge"
    links:
      - kube-apiserver

  kube-proxy:
    container_name: kube-proxy
    hostname: kube-proxy
    image: kube-proxy:latest
    restart: always
    network_mode: "bridge"
    links:
      - kube-apiserver
    depends_on:
      - kubelet

