＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝

############################
# gitlab.yml configuration #
############################

external_url "http://10.62.100.88"
gitlab_rails['gitlab_ssh_host'] = "10.62.100.88"
gitlab_rails['gitlab_shell_ssh_port'] = 10022


gitlab_rails['smtp_enable'] = true
gitlab_rails['smtp_address'] = "smtp.126.com"
gitlab_rails['smtp_port'] = 25
gitlab_rails['smtp_user_name'] = "goldon"
gitlab_rails['smtp_password'] = "Aa888888"
gitlab_rails['smtp_enable_starttls_auto'] = true
gitlab_rails['gitlab_email_from'] = "qgd365@126.com"

＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝



version: '2'
services:
  gitlab:
    container_name: 'gitlab'
    hostname: 'gitlab.registry.com'
    restart: always
    image: gitlab/gitlab-ce:latest
    network_mode: 'bridge'
    expose:
      - '443'
      - '80'
      - '22'
    ports:
      - '443:443'
      - '80:80'
      - '10022:22'
    volumes:
      - /var/lib/volumes/gitlab/config:/etc/gitlab
      - /var/lib/volumes/gitlab/logs:/var/log/gitlab
      - /var/lib/volumes/gitlab/data:/var/opt/gitlab
    
